// Generated by uniffi-bindgen-react-native
#include "react-native-lni-lexe.h"
#include "generated/react_native_lexe.hpp"

namespace lnilexe {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeReactNativeLexe::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}