// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "LNI",
    platforms: [
        .iOS(.v14),
        .macOS(.v12)
    ],
    products: [
        .library(
            name: "LNI",
            targets: ["LNI", "lniFFI"]
        ),
    ],
    targets: [
        // Swift bindings generated by UniFFI
        .target(
            name: "LNI",
            dependencies: ["lniFFI"],
            path: "bindings/swift/Sources/LNI"
        ),
        // Binary XCFramework containing the native library
        // 
        // The URL and checksum below identify the matching published archive.
        // When creating a new release:
        // 1. Build the XCFramework: ./bindings/swift/build.sh --release --ios
        // 2. Rename to lniFFI.xcframework
        // 3. Create zip: zip -r lniFFI.xcframework.zip lniFFI.xcframework
        // 4. Calculate checksum: swift package compute-checksum lniFFI.xcframework.zip
        // 5. Upload the zip to the GitHub release
        // 6. Update the URL version and checksum below
        //
        // For local development, replace this with:
        // .binaryTarget(name: "lniFFI", path: "bindings/swift/lniFFI.xcframework")
        .binaryTarget(
            name: "lniFFI",
            url: "https://github.com/lightning-node-interface/lni/releases/download/swift-v0.2.5-lexe-onchain/lniFFI.xcframework.zip",
            checksum: "d06f6acb60e070158062418c468ca3985165a9f8cbbe9792a2a77e335a7a680e"
        )
    ]
)
