// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "LNI",
    platforms: [
        .iOS(.v14),
        .macOS(.v12)
    ],
    products: [
        .library(
            name: "LNI",
            targets: ["LNI", "lniFFI"]
        ),
    ],
    targets: [
        // Swift bindings generated by UniFFI
        .target(
            name: "LNI",
            dependencies: ["lniFFI"],
            path: "Sources/LNI"
        ),
        // Binary XCFramework containing the native library
        // To use a local build, replace this with:
        // .binaryTarget(name: "lniFFI", path: "lniFFI.xcframework")
        .binaryTarget(
            name: "lniFFI",
            url: "https://github.com/lightning-node-interface/lni/releases/download/v0.1.0/lniFFI.xcframework.zip",
            checksum: "SHA256_CHECKSUM_HERE"
        )
    ]
)
