// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "LNI",
    platforms: [
        .iOS(.v14),
        .macOS(.v12)
    ],
    products: [
        .library(
            name: "LNI",
            targets: ["LNI", "lniFFI"]
        ),
    ],
    targets: [
        // Swift bindings generated by UniFFI
        .target(
            name: "LNI",
            dependencies: ["lniFFI"],
            path: "Sources/LNI"
        ),
        // Binary XCFramework containing the native library
        // 
        // NOTE: The checksum below is a placeholder. When creating a new release:
        // 1. Build the XCFramework: ./build.sh --release --ios
        // 2. Rename to lniFFI.xcframework
        // 3. Create zip: zip -r lniFFI.xcframework.zip lniFFI.xcframework
        // 4. Calculate checksum: swift package compute-checksum lniFFI.xcframework.zip
        // 5. Upload the zip to the GitHub release
        // 6. Update the URL version and checksum below
        //
        // For local development, replace this with:
        // .binaryTarget(name: "lniFFI", path: "lniFFI.xcframework")
        .binaryTarget(
            name: "lniFFI",
            url: "https://github.com/lightning-node-interface/lni/releases/download/v0.1.0/lniFFI.xcframework.zip",
            checksum: "SHA256_CHECKSUM_HERE"
        )
    ]
)
