// Generated by uniffi-bindgen-react-native
import installer from './NativeLni';

// Register the rust crate with Hermes
installer.installRustCrate();

// Export the generated bindings to the app.
export * from './generated/lni';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as lni from './generated/lni';

// Initialize the generated bindings: mostly checksums, but also callbacks.
lni.default.initialize();

// Export the crates as individually namespaced objects.
export default {
  lni,
};
