// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-lni.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNLniSpec.h"

@interface Lni : NSObject <NativeLniSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Lni : NSObject <RCTBridgeModule>
#endif

@end