// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "lni-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNLniReactNativeSpec.h"

@interface LniReactNative : NSObject <NativeLniReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface LniReactNative : NSObject <RCTBridgeModule>
#endif

@end