// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-lni-lexe.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "ReactNativeLexeSpec.h"

@interface LniLexe : NSObject <NativeLniLexeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface LniLexe : NSObject <RCTBridgeModule>
#endif

@end