// Generated by uniffi-bindgen-react-native
#include "react-native-lni.h"
#include "generated/lni.hpp"
#include "generated/lni_uniffi.hpp"

namespace lni {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeLni::registerModule(runtime, callInvoker);
		NativeLniUniffi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}